# Generated by Django 5.0.2 on 2024-02-15 11:44

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='project/default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 150], upload_to='project/images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
